auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("listing_view/<int:id>/", views.listing_view, name="listing_view"),
    path("create_listing/", views.create_listing, name="create_listing"),
    path("edit_listing/<int:id>/", views.edit_listing, name="edit_listing"),
    path("set_bid/<int:id>/", views.set_bid, name="set_bid"),
    path("close_auction/<int:id>/", views.close_auction, name="close_auction"),
    path("my_wins/", views.my_wins, name="my_wins"),
    path("comment/<int:id>", views.comment, name="comment"),
    path("watchlist/", views.watchlist, name="watchlist"),
    path("view_watchlist/", views.view_watchlist, name='view_watchlist'),
    path("categories/", views.categories, name='categories'),
    path("categories/<str:category>/", views.category_list, name="category_list"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models
from datetime import datetime


# class User(AbstractUser):
#     username = models.CharField(max_length=150, unique=True)
#     watchlist = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name='watchlist')
    

class AuctionListing(models.Model):
    categories_choices = (
        ('Fashion', 'Fashion'),
        ('Toys', 'Toys'),
        ('Electronics', 'Electronics'),
        ('Home', 'Home'),
        ('Books', 'Books'),
        ('Other', 'Other')
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="auction_listings")
    product = models.CharField(max_length=200)
    photo = models.ImageField(blank=True,  null=True, upload_to='uploads/')
    description = models.TextField(max_length=500)
    starting_bid = models.FloatField(default=0.01)
    current_price = models.FloatField()
    current_winner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="current_winner", blank=True, null=True)
    active = models.BooleanField(default=True)
    categorie = models.CharField(max_length=15, choices=categories_choices, blank=True, null=True, default='Other')

    def __str__(self):
        return f"{self.product}: $ {self.current_price}"


class Watchlist(models.Model):
    auction_listings = models.ManyToManyField(AuctionListing)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='watchlist', primary_key=True)



class Bid(models.Model):
    auction_listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name="bids")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")
    value = models.FloatField()


class Comment(models.Model):
    date = models.DateField(auto_created=True, default=datetime.now())
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    auction_listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name="comments")
    text = models.TextField(max_length=500)

auctions/forms.py
from django import forms
from .models import AuctionListing


class AuctionListingForm(forms.ModelForm):
    class Meta:
        model = AuctionListing
        fields = [
            'product',
            'photo',
            'description',
            'starting_bid',
            'categorie'
            # 'current_price',
        ]

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect, HttpResponseForbidden

from django.shortcuts import render, redirect
from django.urls import reverse
import os
from .models import AuctionListing, User, Bid, Comment, Watchlist
from .forms import AuctionListingForm

from django.contrib import messages
from django.contrib.messages import constants

from django.core.exceptions import ObjectDoesNotExist

def index(request):
    active_listings = AuctionListing.objects.filter(active=True).all()
    
    return render(request, "auctions/index.html", context={'active_listings': active_listings})

@login_required(login_url='auctions/login.html')
def create_listing(request):
    if request.method == "GET":
        return render(request, "auctions/create_listing.html", {
            'form': AuctionListingForm()
        })
    if request.method == "POST":
        form = AuctionListingForm(request.POST, request.FILES)
        if form.is_valid():
            new_listing = form.save(commit=False)
            new_listing.author = request.user
            new_listing.current_price = new_listing.starting_bid
            new_listing.save()
            return redirect(f"/listing_view/{new_listing.id}/")
        for error in form.errors.values():
            messages.add_message(request=request, level=constants.ERROR, message=error)

@login_required(login_url='auctions/login.html')
def edit_listing(request, id):
    if request.method == 'GET':
        new_listing = AuctionListing.objects.get(id=id)
        assert new_listing.author == request.user, HttpResponseForbidden()
        form = AuctionListingForm(initial={
            'product': new_listing.product,
            'photo': new_listing.photo,
            'description': new_listing.description,
            'starting_bid': new_listing.starting_bid
        })
        return render(request, "auctions/edit_listing.html", {'form': form, 'id':id})

    if request.method == 'POST':
        listing = AuctionListing.objects.get(id=id)
        assert listing.author == request.user, HttpResponseForbidden()
        listing.product = request.POST.get('product')
        listing.categorie = request.POST.get('categorie')
        listing.starting_bid = request.POST.get('starting_bid')
        listing.description = request.POST.get('description')
        listing.current_winner = listing.current_winner
        if len(request.FILES) == 0:
            listing.photo = listing.photo
        else:
            os.remove(listing.photo.path)
            listing.photo = request.FILES.get('photo')
        listing.save()
        messages.add_message(request, constants.SUCCESS, message="Listing updated.")
        return redirect(f'/listing_view/{listing.id}/')

def set_bid(request, id):
    if request.method == 'POST':
        bid = request.POST.get('bid')
        listing = AuctionListing.objects.get(id=id)
        if float(bid) <= listing.current_price:
            messages.add_message(request, constants.ERROR, message="Bid has to be greater than current price.")
            return redirect(f'/listing_view/{listing.id}/')
        listing.current_price = bid
        listing.current_winner = request.user
        listing.save()
        messages.add_message(request, constants.SUCCESS, message="Your bid has been placed!")
        return redirect(f"/listing_view/{listing.id}")

def listing_view(request, id):
    listing = AuctionListing.objects.get(id=id)
    comments = Comment.objects.filter(auction_listing=listing).order_by('date')
    try:
        watchlist = Watchlist.objects.get(user=request.user.id)
        if listing in watchlist.auction_listings.all():
            watchlisted = True
        else:
            watchlisted = False
    except ObjectDoesNotExist:
        watchlisted = False

    return render(request, "auctions/view.html", {
        'listing': listing,
        'comments': comments,
        'watchlisted': watchlisted,
    })

def close_auction(request, id):
    if request.method == 'GET':
        listing = AuctionListing.objects.get(id=id)
        if listing.author == request.user and listing.active == True:
            listing.active = False
            listing.save()
            return redirect(f"/listing_view/{listing.id}")

def comment(request, id):
    if request.method == 'POST':
        listing = AuctionListing.objects.get(id=id)
        text = request.POST.get("comment")
        new_comment = Comment()
        new_comment.text = text
        new_comment.auction_listing = listing
        new_comment.author = request.user
        new_comment.save()
        return redirect(f"/listing_view/{listing.id}")

@login_required
def my_wins(request):
    if request.method == 'GET':
        winned_auctions = AuctionListing.objects.filter(active=False, current_winner=request.user)
        return render(request, "auctions/my_wins.html", {'winned_auctions': winned_auctions})

@login_required(login_url='auctions/login.html')
def watchlist(request):
    if request.method == 'GET':
        if not request.GET.get('listing_id'):
            watchlist = Watchlist.objects.get(user=request.user)
            return render(request, "auctions/watchlist.html", {'watchlist': watchlist})

        listing = AuctionListing.objects.get(id=request.GET.get('listing_id'))
        try:
            watchlist = Watchlist.objects.get(user=request.user.id)
        except:
            watchlist = ''
        if watchlist:
            # If listing already in watchlist, remove listing from watchlist
            if listing in watchlist.auction_listings.all():
                watchlist.auction_listings.remove(listing)
                watchlist.save()
                return render(request, "auctions/view.html", {
                    'listing': listing,
                    'watchlisted': False,
                })    

            watchlist.auction_listings.add(listing)
            watchlist.save()
            return render(request, "auctions/view.html", {
                'listing': listing,
                'watchlisted': True,
                })
        auction_listing = AuctionListing.objects.get(id=request.GET.get('listing_id'))
        watchlist = Watchlist.objects.create(user=request.user)
        watchlist.auction_listings.add(auction_listing)
        watchlist.save()
        return render(request, "auctions/view.html", {
                'listing': listing,
                'watchlisted': True,
                })

@login_required(login_url='auctions/login.html')
def view_watchlist(request):
    watchlist = Watchlist.objects.get(user=request.user.id)
    return render(request, 'auctions/watchlist.html', {
        'listings': watchlist.auction_listings.all(),
    })

def categories(request):
    categories = [j for (i, j) in AuctionListing.categories_choices]
    return render(request, 'auctions/categories.html', {
        'categories': categories,
    })

def category_list(request, category: str):
    listings = AuctionListing.objects.filter(categorie=category)
    return render(request, 'auctions/category_view.html', {
        'listings': listings
    })

def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    
    <table class="table">
        {% for category in categories %}
        <td>
            <a href="{% url 'auctions:category_list' category %}">
                {{category}}
            </a>
        </td>
            {% endfor %}
    </table>
    
{% endblock %}

auctions/templates/auctions/category_view.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>

    {% for listing in listings %}
    <a href="{% url 'auctions:listing_view' listing.id %}">
        <ul>
            <li>
                <div class="container">
                    <div class="row">
                        <div class="col col-sm">
                            {{listing.product}}            
                        </div>
                        <div class="col col-sm">
                            {{listing.current_price}}                
                        </div>
                        <div class="col col-lg">
                            {{listing.description}}
                        </div>
                        <div class="col col-lg">
                            {% if listing.photo %}
                                <img src="{{listing.photo.url}}" alt="" style="max-width: 50%;">
                            {% else %}
                                No picture
                            {% endif %}
                        </div>
                        <div class="col col-sm">
                            {{listing.author}}
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </a>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/create_listing.html
{% extends "auctions/layout.html" %}

{% block body %}

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <h2>New Listing</h2>

    <form action="{% url 'auctions:create_listing' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{form.as_p}}
            <input type="submit" value="Save">
        </div>
    </form>
    
    
{% endblock %}

auctions/templates/auctions/edit_listing.html
{% extends "auctions/layout.html" %}

{% block body %}

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <h2>Edit Listing</h2>

    <form action="{% url 'auctions:edit_listing' id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{form.as_p}}
            <input type="submit" value="Save">
        </div>
    </form>
    
    
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>

    <ul class="list-group">
    {% for listing in active_listings %}
    <a href="{% url 'auctions:listing_view' listing.id %}">
            <li class="list-group-item">
                <div class="container">
                    <div class="row">
                        <div class="col col-sm">
                            {{listing.product}}            
                        </div>
                        <div class="col col-sm">
                            {{listing.current_price}}                
                        </div>
                        <div class="col col-lg">
                            {{listing.description}}
                        </div>
                        <div class="col col-lg">
                            {% if listing.photo %}
                                <img src="{{listing.photo.url}}" alt="" style="max-width: 50%;" class="rounded-sm">
                            {% else %}
                                No picture
                            {% endif %}
                        </div>
                        <div class="col col-sm">
                            {{listing.author}}
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </a>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col align-self-end">
                    {% if user.is_authenticated %}
                        <span>Signed in as </span>
                        
                         <strong> {{ user.username }} </strong>.
                    {% else %}
                        Not signed in.
                    {% endif %}
                </div>
                <div class="row">
                </div>
            </div>
            <div class="container">

                <nav class="navbar navbar-expand-lg navbar-light bg-ligh">
                    <a class="navbar-brand" href="{% url 'auctions:index' %}">Auctions</a>
                    <div class="collapse navbar-collapse" id="navbarText">
                        
                        <!-- Navbar content -->
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                            </li>
                            {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auctions:create_listing' %}">Create listing</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auctions:view_watchlist' %}">Watchlist</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auctions:my_wins' %}">My wins</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                                </li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
            </div>

            </div>
        <hr>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/view.html
{% extends "auctions/layout.html" %}


{% block title %}
Auction details
{% endblock title %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <h2>Listing Details</h2>
            </div>
            {% if listing.author != request.user %}
            <div class="col">
                <form action="{% url 'auctions:watchlist' %}" method="get">
                    {% if not watchlisted %}
                        <input type="hidden" name="listing_id" value="{{listing.id}}">
                        <button class="btn btn-primary" type="submit">add to watchlist</button>
                    {% else %}
                        <input type="hidden" name="listing_id" value="{{listing.id}}">
                        <button class="btn btn-danger" type="submit">remove from watchlist</button>
                    {% endif %}
                </form>
            </div>
            {% endif %}
        </div>
    </div>

    {% if messages %}
        {% for message in messages %}
            <div class="alert {{message.tags}}">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}

    {% if request.user == listing.current_winner and listing.active == False %}
            <h3>You won this auction!</h3>
    {% endif %}
    <br>        
    <div class="container">
        <table>
            <thead>
                <tr>
                    <h3>{{listing.product.capitalize}}</h3> <br>
                </tr>
            </thead>
                <tr>
                    <th>
                        Category:
                    </th>
                    <td>{{listing.categorie}}</td>
                </tr>
                <tr>
                    <th>
                        Current price:
                    </th>
                    <td>{{listing.current_price}}</td>
                </tr>
                <tr>
                    <th>
                        Owner:
                    </th>
                    <td>{{listing.author}}</td>
                </tr>
                <tr>
                    <th>
                        Current winner:
                    </th>
                    <td>
                        {% if listing.current_winner %}
                            {{listing.current_winner}} <br>
                        {% else %}
                            No bids yet <br> 
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <th>
                        Description:
                    </th>
                    <td>
                        {{listing.description}}
                    </td>
                </tr>
                <tr>
                    <th>
                        Status:
                    </th>
                    <td>
                        {% if listing.active %}
                                Active <br>
                        {% else %}
                                Inactive <br>
                        {% endif %}
                    </td>
                </tr>
        </table>
    </div>
    <br>
    <div class="container">
        {% if listing.photo %}
            <img class="rounded-lg" src="{{listing.photo.url}}" alt="" style="max-width: 30%;"><br>
        {% endif %}
    </div>
    <br>
    <div class="container">

        {% if request.user == listing.author and listing.active == True %}
            <a class="btn btn-secondary" href="{% url 'auctions:edit_listing' listing.id %}">
                Edit
            </a>
            
            <!-- Close Auction Modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#closeAuctionModal">
                Close Auction
            </button>
            <div class="modal fade" id="closeAuctionModal" tabindex="-1" role="dialog" aria-labelledby="closeAuctionModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="closeAuctionModalLabel">Are you sure to close this auction?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    <div class="modal-body">
                    Winner: {{listing.current_winner}} <br>
                    Price: {{listing.current_price}}
                    </div>
    
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-danger" href="{% url 'auctions:close_auction' listing.id %}">Finish this auction</a>
                    </div>
                </div>
                </div>
            </div>
            
        {% else %}
            {% if request.user.is_authenticated and listing.active == True %}
                <form action="{% url 'auctions:set_bid' listing.id %}" method="post">
                    {% csrf_token %}
                    <h4>Set a Bid:</h2>
                        <input type="number" min="{{listing.current_price}}" step="any" name="bid" placeholder="{{listing.current_price}}">
                        <button class="btn btn-secondary" type="submit">
                            Set bid
                        </button>
                </form>
            {% endif %}
        {% endif %}
    </div>
    
<!-- Comments -->
<div class="container">
    <div class="row">
        <div class="col">
            <h3>Comments</h3>
        </div>
        
        <!-- Comment Modal -->
        {% if request.user.is_authenticated %}
        <div class="col">
            <button type="button" class="badge badge-primary" data-toggle="modal" data-target="#commentModal">
                leave a comment
            </button>
        </div>

        <div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModal" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="commentLabel">New Comment:</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form action="{% url 'auctions:comment' listing.id %}" method="post"> {% csrf_token %}
                    <div class="modal-body">
                    <textarea class="form-control" name="comment" cols="30" rows="10">
                        
                    </textarea>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button class="btn btn-primary" type="submit">Post comment</button>
                    </div>
                </form>
            </div>
            </div>
        </div>
        {% endif %}

    </div>
    <table class="table">
        <thead>
            <th>user</th>
            <th>comment</th>
            <th>date</th>
        </thead>
        {% for comment in comments  %}
        <tr>
            <td>
                {{comment.author}}
            </td>
            <td>
                {{comment.text}}
            </td>
            <td>
                {{comment.date}}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

{% endblock %}